### ISSUE TITLE
POSIXlt in standard unambiguous format for Spanish Locales

### ISSUE THREAD

**Issue by timtrice** [ropensci/rrricanes#110]
### Error Message

```
Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format
```

### Reproducible Example

```r
library(dplyr)
library(rrricanes)
library(rrricanesdata)

Sys.setlocale("LC_ALL","Spanish_Costa Rica.1252")

ds <- get_storms() %>%
  filter(Name == "Hurricane Harvey") %>%
  pull(Link) %>% 
  get_storm_data(products = c("discus", "fstadv"))
```

### Session Info

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Costa Rica.1252  LC_CTYPE=Spanish_Costa Rica.1252    LC_MONETARY=Spanish_Costa Rica.1252 LC_NUMERIC=C                       
[5] LC_TIME=Spanish_Costa Rica.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2          rrricanesdata_0.0.1.4 rrricanes_0.2.0.7     dplyr_0.7.4          

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13     assertthat_0.2.0 crul_0.4.0       R6_2.2.2         magrittr_1.5     httr_1.3.1       stringi_1.1.5    rlang_0.1.2     
 [9] curl_2.8.1       xml2_1.1.1       tools_3.4.1      stringr_1.2.0    glue_1.1.1       purrr_0.2.3      compiler_3.4.1   pkgconfig_2.0.1 
[17] rvest_0.3.2      bindr_0.1        tibble_1.3.4    
> 
```

**Comment by timtrice** [comment]
The locale setting, I believe is creating this error. In `scrape_date`, the date is reformatted using `as.Date` but without a time zone. 

[See func scrape_date line #130](https://github.com/ropensci/rrricanes/blob/d631a32a3e3f26c018a07b6d86457907df99443b/R/scrapers.R#L21)

**Comment by santiagomota** [comment]
On ubuntu, you can use Sys.setlocale("LC_ALL", "en_US.UTF-8")

**Comment by timtrice** [comment]
The user would set this on their end, correct?

**Comment by santiagomota** [comment]
No. Sorry Tim. I just think so, but I am trying to work it in a Ubuntu with a es utf-8 locales, but it does not work. Same error. I will keep trying and keep you informed.

**Comment by timtrice** [comment]
Appreciate it. I haven't put a focus on this issue. If you are able to get it resolved, happy to take a PR. Thank you for trying.

**Comment by santiagomota** [comment]
I think the issue is with linux locales. I can obtain discus data with str 
List of 1
 $ discus:Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	43 obs. of  6 variables:
  ..$ Status  : chr [1:43] "Potential Tropical Cyclone" "Tropical Storm" "Tropical Storm" "Tropical Storm" ...
  ..$ Name    : chr [1:43] "Nine" "Harvey" "Harvey" "Harvey" ...
  ..$ Adv     : num [1:43] 1 2 3 4 5 6 7 8 9 10 ...
  ..$ Date    : POSIXct[1:43], format: "2017-08-17 15:00:00" "2017-08-17 21:00:00" "2017-08-18 03:00:00" "2017-08-18 09:00:00" ...
  ..$ Key     : chr [1:43] "AL092017" "AL092017" "AL092017" "AL092017" ...
  ..$ Contents: chr [1:43] "\nZCZC MIATCDAT4 ALL\nTTAA00 KNHC DDHHMM\n\nPOTENTIAL TROPICAL CYCLONE NINE DISCUSSION NUMBER   1\nNWS NATIONAL"| __truncated__ "\nZCZC MIATCDAT4 ALL\nTTAA00 KNHC DDHHMM\n\nTROPICAL STORM HARVEY DISCUSSION NUMBER   2\nNWS NATIONAL HURRICANE"| __truncated__ "\nZCZC MIATCDAT4 ALL\nTTAA00 KNHC DDHHMM\n\nTROPICAL STORM HARVEY DISCUSSION NUMBER   3\nNWS NATIONAL HURRICANE"| __truncated__ "\nZCZC MIATCDAT4 ALL\nTTAA00 KNHC DDHHMM\n\nTROPICAL STORM HARVEY DISCUSSION NUMBER   4\nNWS NATIONAL HURRICANE"| __truncated__ ...

**Comment by elinw** [comment]
@lismariea is working on this one.

**Comment by elinw** [comment]
This should work now.
